# For configuration property names that use quotes, do not split the string inside the quotes
quarkus:
  log:
    category:
      "io.quarkus.category":
        level: INFO
  http:
    port: 8081
connector:
  config:
    file: config/connectors.yaml
    
