/*
 * Copyright 2024 ranSprd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package net.kiar.collectorr.connector;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import java.util.Optional;
import net.kiar.collectorr.config.MappingsConfigLoader;
import net.kiar.collectorr.config.model.TopicConfig;
import net.kiar.collectorr.connector.mqtt.mapping.TopicCache;
import net.kiar.collectorr.metrics.MetricDefinition;
import net.kiar.collectorr.metrics.PrometheusCounterGauge;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.Test;

/**
 *
 * @author ranSprd
 */
public class ArrayPayloadTest {
    
    private record Result(List<PrometheusCounterGauge> metrics, TopicCache topicCache) {};
    
    private Result build(String config) throws IOException {
        String topicPath = "/get_livedata_info";
//        MappingsConfigLoader conf = MappingsConfigLoader.readFromFile("src/test/resources/http/ecowitt-mappings.yaml");
        MappingsConfigLoader conf = MappingsConfigLoader.readContent(config);
        
        TopicConfig topicToTest = conf.getTopicsToObserve().get(0);
        TopicCache topicCache = TopicCache.buildTopicPattern(topicToTest).get();
        
        String message = Files.readString( Paths.get("src/test/resources/http/payloads/ecowitt.json"));
        
        List<PrometheusCounterGauge> result = topicCache.getTopicProcessor().consumeMessage(message, topicPath);
        return new Result(result, topicCache);
    }
    
    private final String configMinimalSetup = """
topics:
- topic: /get_livedata_info
  metrics:
  - valueField: common_list.*.val
""";
    @Test
    public void testAutoGeneratedLabels() throws IOException {
        Result result = build(configMinimalSetup);
        assertNotNull(result.metrics);
        assertEquals(12, result.metrics.size());
        
        Optional<PrometheusCounterGauge> anyGauge = result.metrics.stream()
                .filter(gauge -> gauge.getName().endsWith("list.#0.val"))
                .findAny();
        assertTrue(anyGauge.isPresent());
        assertEquals(anyGauge.get().getNumberOfLabels(), 3);
        assertEquals( "0x02", anyGauge.get().getLabelValue("common_list.#0.id"));
        assertEquals( "C", anyGauge.get().getLabelValue("common_list.#0.unit"));
        assertEquals( "ecowitt", anyGauge.get().getLabelValue("device"));
        System.out.println( anyGauge.get().toMetricString());
                
        
        List<MetricDefinition> metricDefs = result.topicCache.getTopicProcessor().getDefinedMetrics();
        assertEquals(1, metricDefs.size());
        
        MetricDefinition firstMetric = anyGauge.get().getMetricDefinition();
        assertEquals(3, firstMetric.getLabels().size());
    }
    
    private final String configWithSomeLabels = """
topics:
- topic: /get_livedata_info
  metrics:
  - valueField: common_list.*.val
    labels: [common_list.*.id, common_list.*.unit|unit]                                            
""";
    @Test
    public void testWithLabelSettings() throws IOException {
    
        Result result = build(configWithSomeLabels);
        Optional<PrometheusCounterGauge> anyGauge = result.metrics.stream()
                .filter(gauge -> gauge.getName().endsWith("list.#0.val"))
                .findAny();
        assertTrue(anyGauge.isPresent());
//        System.out.println( anyGauge.get().toMetricString());

        assertEquals(anyGauge.get().getNumberOfLabels(), 2);
        assertEquals( "0x02", anyGauge.get().getLabelValue("common_list.#0.id"));
        assertEquals( "C", anyGauge.get().getLabelValue("unit"));
    }
    
    
    
    private final String configWithMapping = """
topics:
- topic: /get_livedata_info
  mappings:
  - label:
    source: common_list.*.id
    target: detailedName
    map:
       0x02 : temperature
       0x01 : unknown
       0x07 : humidity
       0x15 : solar
                                             
                                             
  metrics:
  - name: "weather_{detailedName}"
    valueField: common_list.*.val
    labels: [common_list.*.id|id, detailedName]                                            
""";
    @Test
    public void testInsertedMappings() throws IOException {
    
        Result result = build(configWithMapping);
        Optional<PrometheusCounterGauge> anyGauge = result.metrics.stream()
                .filter(gauge -> gauge.getMetricDefinition().getFieldOfValue().getFieldName().getFullName().endsWith("*.val"))
                .findAny();
        assertTrue(anyGauge.isPresent());
        System.out.println( anyGauge.get().toMetricString());

        assertEquals(2, anyGauge.get().getNumberOfLabels());
        assertEquals("weather_temperature", anyGauge.get().getName());
        assertEquals( "0x02", anyGauge.get().getLabelValue("id"));
        assertEquals( "temperature", anyGauge.get().getLabelValue("detailedName"));
    }
}
